name: Continuous Integration

on: [ push, pull_request ]

jobs:
  build_and_test:
    name: Build & Test (OS ${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-12, ubuntu-22.04, windows-2022 ]
        python-version: [ '3.10', '3.11' ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.2

      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install -U pip==23.1

      - name: Install pipx
        run: |
          python -m pip install pipx==1.2.0

      - name: Install Poetry
        run: |
          pipx install poetry==1.4.2

      - name: Install dependencies
        run: |
          poetry install

      - name: Run Behave tests
        run: |
          poetry run behave
