name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.2

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: |
          python -m pip install -U pip==23.1

      - name: Install pipx
        run: |
          python -m pip install pipx==1.2.0

      - name: Install Poetry using pipx
        run: |
          pipx install poetry==1.4.2

      - name: Install dependencies
        run: |
          poetry install

      - name: Change to project root directory
        run: |
          cd ${{ github.workspace }}

      - name: Run Behave tests
        run: |
          poetry run behave
