name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '36 14 * * 5'

jobs:
  codeql_analyze:
    name: CodeQL analysis
    runs-on: ubuntu-22.04

    env:
      CODEQL_ACTION_VERSION: v2.2.12
      LANGUAGE: python

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@$CODEQL_ACTION_VERSION
        with:
          languages: $LANGUAGE

      - name: Autobuild
        uses: github/codeql-action/autobuild@$CODEQL_ACTION_VERSION

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@$CODEQL_ACTION_VERSION
        with:
          category: /language:$LANGUAGE
